const Doctor = require('../models/Doctor');
const Service = require('../models/Service');
const Appointment = require('../models/Appointment');

const doctorsData = [
  {
    name: 'Dr. Paavai Senthil',
    title: 'Chief Dermatologist & Aesthetic Physician',
    department: 'Dermatology & Aesthetic Medicine',
    deptKey: 'skin',
    qualifications: 'MBBS, MD(DVL), FRGUHS (Aesthetic Dermatology)',
    experience: '6+ Years Experience',
    experienceYears: 6,
    memberships: ['IADVL (Indian Association of Dermatologists, Venereologists and Leprologists)', 'ACSI (Association of Cutaneous Surgeons of India)', 'INSTED (International Society of Teledermatology)'],
    phone: '+91 80480 53215',
    directMobile: '93427 90784',
    email: 'hospitalpaavai@gmail.com',
    image: '/img/doctor1.webp',
    bio: 'Dr. Paavai Senthil is a renowned Dermatologist and Aesthetic Physician with specialized Fellowship training from FRGUHS in Aesthetic Dermatology. She has over 6 years of expertise delivering evidence-based dermatological care, anti-aging therapies, non-surgical facial rejuvenation, acne scar revision, and hair restoration.',
    specialties: [
      'Aesthetic Dermatology & Photo Facials',
      'Hydra Facial & Skin Rejuvenation',
      'Laser Hair Removal & Tattoo Revision',
      'Botox, Fillers & Collagen Threads',
      'GFC & PRP Hair Restoration',
      'Acne Scar Subcision & RF Microneedling'
    ],
    consultationDays: 'Monday to Saturday',
    consultationHours: '10:00 AM - 01:30 PM & 04:30 PM - 07:30 PM',
    isAvailable: true,
    roomNumber: 'Skin & Aesthetic OPD - Suite 101'
  },
  {
    name: 'Dr. Nivas Sengottaiyan',
    title: 'Consultant Dermatologist & Dermatosurgeon',
    department: 'Dermatology & Aesthetic Medicine',
    deptKey: 'skin',
    qualifications: 'MBBS, MD (DVL)',
    experience: '6+ Years Experience',
    experienceYears: 6,
    memberships: ['IADVL (Life Member)', 'IMA Salem Branch'],
    phone: '+91 80480 53215',
    directMobile: '+91 80480 53215',
    email: 'hospitalpaavai@gmail.com',
    image: '/img/doctor2.webp',
    bio: 'Dr. Nivas Sengottaiyan is an experienced Dermatologist specializing in clinical dermatology, complex skin allergies, pigmentation disorders, pediatric skin conditions, and minor dermato-surgical procedures including cyst excision, keloid management, and cryotherapy.',
    specialties: [
      'Clinical Dermatology & Chronic Skin Conditions',
      'Pigmentation & Melasma Management',
      'Cryotherapy & Intralesional Injections',
      'Nail Surgery & Earlobe Repair',
      'Keloid Surgery & Scar Revision',
      'Psoriasis & Atopic Dermatitis Protocol'
    ],
    consultationDays: 'Monday to Saturday',
    consultationHours: '09:30 AM - 01:00 PM & 05:00 PM - 08:00 PM',
    isAvailable: true,
    roomNumber: 'Clinical Dermatology OPD - Suite 102'
  },
  {
    name: 'Dr. R. Soundararajan',
    title: 'Senior Consultant Ophthalmologist & Micro-Surgeon',
    department: 'Ophthalmology (Eye Care)',
    deptKey: 'eye',
    qualifications: 'MBBS, MS (Ophthalmology), FICO (UK), Cornea & Refractive Fellowship',
    experience: '9+ Years Experience',
    experienceYears: 9,
    memberships: ['All India Ophthalmological Society (AIOS)', 'Tamil Nadu Ophthalmic Association (TNOA)', 'Cornea Society of India'],
    phone: '+91 80480 53215',
    directMobile: '+91 80480 53215',
    email: 'hospitalpaavai@gmail.com',
    image: '/img/building.webp',
    bio: 'Dr. R. Soundararajan leads the Ophthalmology Department at Paavai Hospital, bringing high precision in sutureless Phacoemulsification Cataract Surgery, premium intraocular lens implantation (Toric/Multifocal), LASIK evaluation, and corneal diagnostics.',
    specialties: [
      'Micro-Incision Cataract Surgery (Phaco)',
      'Premium Intraocular Lens Implantation (IOL)',
      'Refractive Surgery & LASIK Consultation',
      'Cornea Clinic & Topography Analysis',
      'Dry Eye & Ocular Surface Disease'
    ],
    consultationDays: 'Monday to Saturday',
    consultationHours: '09:00 AM - 01:30 PM & 04:00 PM - 07:00 PM',
    isAvailable: true,
    roomNumber: 'Ophthalmology Clinic - Suite 201'
  },
  {
    name: 'Dr. K. Meenakshi',
    title: 'Vitreo-Retina & Glaucoma Specialist',
    department: 'Ophthalmology (Eye Care)',
    deptKey: 'eye',
    qualifications: 'MBBS, MS (Ophthal), FVRS (Vitreo-Retina)',
    experience: '7+ Years Experience',
    experienceYears: 7,
    memberships: ['Vitreo Retinal Society of India (VRSI)', 'Glaucoma Society of India (GSI)', 'AIOS'],
    phone: '+91 80480 53215',
    directMobile: '+91 80480 53215',
    email: 'hospitalpaavai@gmail.com',
    image: '/img/building.webp',
    bio: 'Dr. K. Meenakshi specializes in advanced retinal diagnostics including Spectral-Domain OCT, Fundus Fluorescein Angiography (FFA), B-Scan Ultrasound, diabetic retinopathy laser photocoagulation, and comprehensive glaucoma screening with applanation tonometry.',
    specialties: [
      'Diabetic & Hypertensive Retinopathy Screening',
      'Optical Coherence Tomography (OCT) & FFA',
      'B-Scan Ocular Ultrasound',
      'Glaucoma Early Detection & Applanation Tonometry',
      'Pediatric Eye Care & Refraction'
    ],
    consultationDays: 'Monday to Saturday',
    consultationHours: '10:00 AM - 02:00 PM & 04:30 PM - 07:30 PM',
    isAvailable: true,
    roomNumber: 'Retina & Glaucoma Center - Suite 202'
  }
];

const servicesData = [
  // Eye Care Services
  {
    name: 'Advanced Cataract Surgery & Evaluation',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Surgical Ophthalmology',
    shortDescription: 'Micro-incision sutureless phacoemulsification with premium monofocal, toric, and multifocal IOL implants.',
    fullDescription: 'Our surgical wing utilizes cutting-edge phacoemulsification platforms for swift, painless cataract extraction. Patients receive comprehensive pre-operative optical biometry and access to premium toric and multifocal foldable intraocular lenses that eliminate or reduce reliance on spectacles.',
    benefits: ['Blade-free micro-incision technique', 'Rapid visual recovery within 24-48 hours', 'Daycare procedure with no hospital stay required', 'Correction for astigmatism and presbyopia'],
    suitableFor: ['Patients with blurred or cloudy vision', 'Difficulty driving at night', 'Frequent prescription changes due to age-related lens changes'],
    durationMinutes: 45,
    preparationInfo: 'Please arrange for someone to accompany you. Avoid wearing contact lenses 48 hours prior to biometry evaluation.',
    equipmentUsed: 'Advanced Phaco Platform & Optical Biometer',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Eye'
  },
  {
    name: 'LASIK Consultation & Refractive Suite',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Refractive Eye Care',
    shortDescription: 'Comprehensive refractive screening, corneal topography, and eligibility analysis for freedom from glasses.',
    fullDescription: 'Comprehensive evaluation for individuals seeking refractive correction (Myopia, Hyperopia, Astigmatism). Includes automated corneal curvature mapping, pachymetry, pupil analysis, and dilated fundus examination to assess customized laser vision correction suitability.',
    benefits: ['Detailed suitability assessment report', 'Accurate corneal thickness measurement', 'Expert guidance on personalized refractive choices'],
    suitableFor: ['Adults (18+) with stable spectacle prescription', 'Contact lens wearers looking for permanent vision clarity'],
    durationMinutes: 40,
    preparationInfo: 'Discontinue soft contact lenses for at least 7 days before evaluation.',
    equipmentUsed: 'Corneal Topography & High-Precision Pachymeter',
    isDiagnostic: true,
    isEmergency: false,
    featured: true,
    icon: 'Sparkles'
  },
  {
    name: 'Glaucoma Management & Early Detection',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Clinical Ophthalmology',
    shortDescription: 'High-precision intraocular pressure checks, visual field testing, and optical nerve head analysis.',
    fullDescription: 'Glaucoma is often called the silent thief of sight. Paavai Hospital provides early diagnostic screening using Goldmann Applanation Tonometry, central corneal thickness assessment, gonioscopy, and Humphrey visual field perimeter analysis to protect your optic nerve.',
    benefits: ['Prevent permanent vision loss through early screening', 'Custom medical and laser treatment protocols', 'Regular monitoring schedule for high-risk families'],
    suitableFor: ['Persons above 40 years', 'Individuals with a family history of glaucoma', 'Patients with high intraocular pressure or diabetes'],
    durationMinutes: 30,
    preparationInfo: 'Pupil dilation may be performed; bring UV sunglasses and avoid driving immediately after the test.',
    equipmentUsed: 'Goldmann Applanation Tonometer & Automated Visual Field Analyzer',
    isDiagnostic: true,
    isEmergency: false,
    featured: true,
    icon: 'Activity'
  },
  {
    name: 'Diabetic & Hypertensive Retinopathy Management',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Retina Care',
    shortDescription: 'Specialized fundus screening, digital retinal imaging, and macular edema management.',
    fullDescription: 'Systemic conditions like diabetes and high blood pressure can cause microvascular damage in the retina. We provide specialized screening, non-mydriatic fundus camera analysis, OCT scans, and targeted therapeutic management to prevent vision compromise.',
    benefits: ['Prevents retinal hemorrhages and detachment', 'Micro-vascular grading for systemic health monitoring', 'Prompt therapeutic intervention for macular edema'],
    suitableFor: ['Type 1 and Type 2 Diabetes patients', 'Hypertension patients', 'Anyone experiencing fluctuating blurry vision or floaters'],
    durationMinutes: 35,
    preparationInfo: 'Comprehensive dilated examination requires 1-2 hours of dilation. Bring your recent fasting blood sugar report.',
    equipmentUsed: 'High-Definition Fundus Camera & Spectral-Domain OCT',
    isDiagnostic: true,
    isEmergency: false,
    featured: true,
    icon: 'HeartPulse'
  },
  {
    name: 'Optical Coherence Tomography (OCT)',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Diagnostic Ophthalmology',
    shortDescription: 'High-resolution cross-sectional micro-imaging of the retina, macula, and optic nerve layers.',
    fullDescription: 'Optical Coherence Tomography (OCT) is a non-invasive optical diagnostic imaging method using light waves to capture micrometer-resolution, 3D cross-sectional images of the retina. Essential for diagnosing macular holes, age-related macular degeneration (AMD), and glaucoma.',
    benefits: ['Non-contact and painless imaging', 'Instant micrometer-level structural diagnosis', 'Essential for monitoring treatment efficacy over time'],
    suitableFor: ['Patients suspected of macular edema, wet/dry AMD, or optic disc anomalies'],
    durationMinutes: 20,
    preparationInfo: 'No special preparation needed. Dilating drops may be administered depending on pupil size.',
    equipmentUsed: 'Spectral Domain HD-OCT Diagnostic System',
    isDiagnostic: true,
    isEmergency: false,
    featured: true,
    icon: 'Scan'
  },
  {
    name: 'B-Scan Ocular Ultrasound',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Diagnostic Ophthalmology',
    shortDescription: 'High-frequency acoustic imaging of the posterior segment when ocular media is hazy or opaque.',
    fullDescription: 'Ocular B-Scan Ultrasonography evaluates the internal structures of the eye when clear visualization is obscured by dense cataracts, vitreous hemorrhage, or corneal opacities. Evaluates vitreous detachment, intraocular tumors, and foreign bodies.',
    benefits: ['Safe, non-invasive ultrasound scanning', 'Accurate view of posterior segment behind dense cataracts', 'Immediate diagnostic confirmation'],
    suitableFor: ['Dense mature cataracts', 'Suspected vitreous hemorrhage', 'Eye trauma and post-injury assessment'],
    durationMinutes: 20,
    preparationInfo: 'Gentle probe applied over closed eyelids using acoustic gel.',
    equipmentUsed: 'High-Resolution Diagnostic B-Scan Ultrasound',
    isDiagnostic: true,
    isEmergency: false,
    featured: false,
    icon: 'Radio'
  },
  {
    name: 'Fundus Fluorescein Angiography (FFA)',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Diagnostic Ophthalmology',
    shortDescription: 'Dynamic photographic study of retinal and choroidal blood circulation using fluorescent dye.',
    fullDescription: 'FFA involves injecting a sodium fluorescein vegetable-based dye into the bloodstream to photograph the retinal circulation in real time. It detects micro-aneurysms, vascular blockages, neo-vascularization, and capillary dropouts.',
    benefits: ['Precise mapping of abnormal retinal vessels', 'Crucial roadmap for retinal laser photocoagulation', 'Accurate identification of leakage areas in the macula'],
    suitableFor: ['Diabetic macular edema', 'Retinal vein occlusion (CRVO/BRVO)', 'Central serous chorioretinopathy (CSCR)'],
    durationMinutes: 40,
    preparationInfo: 'Inform the doctor if you have severe asthma, renal impairment, or dye allergies. Fasting for 2 hours before the procedure is recommended.',
    equipmentUsed: 'Digital Fundus Angiography Camera System',
    isDiagnostic: true,
    isEmergency: false,
    featured: false,
    icon: 'Camera'
  },
  {
    name: 'Applanation Tonometry',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Diagnostic Ophthalmology',
    shortDescription: 'Gold-standard precision measurement of intraocular pressure (IOP).',
    fullDescription: 'Goldmann Applanation Tonometry remains the world benchmark for evaluating eye pressure. Provides highly reliable measurements unaffected by common non-contact tonometer artifacts.',
    benefits: ['Highest measurement accuracy available in clinical practice', 'Gentle and painless with topical anesthetic drops', 'Vital for glaucoma detection and progression management'],
    suitableFor: ['Routine eye wellness exams', 'Glaucoma monitoring', 'Post-surgery eye pressure assessment'],
    durationMinutes: 15,
    preparationInfo: 'A mild numbing drop is placed in the eye. Do not rub eyes for 30 minutes following the test.',
    equipmentUsed: 'Slit-Lamp Mounted Goldmann Applanation Tonometer',
    isDiagnostic: true,
    isEmergency: false,
    featured: false,
    icon: 'Gauge'
  },
  {
    name: 'Dry Eye Care & Allergies',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Clinical Ophthalmology',
    shortDescription: 'Meibomian gland evaluation, tear break-up time (TBUT) testing, and customized ocular surface therapy.',
    fullDescription: 'Prolonged digital screen time, AC environments, and atmospheric pollutants in Salem can trigger debilitating dry eye disease and seasonal allergic conjunctivitis. We assess tear film stability, provide warm compression protocols, preservative-free tears, and anti-inflammatory eye drops.',
    benefits: ['Relief from eye burning, redness, and foreign body sensation', 'Improved visual comfort during computer/screen work', 'Targeted anti-allergic protocols without steroid over-dependence'],
    suitableFor: ['IT professionals, students, drivers, and contact lens users with gritty or burning eyes'],
    durationMinutes: 25,
    preparationInfo: 'Refrain from using lubricating drops 2 hours before evaluation to test natural tear film.',
    equipmentUsed: 'Slit-Lamp Biomicroscopy with Fluorescein Tear-Film Staining',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Droplets'
  },
  {
    name: 'Pediatric Eye Care',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Clinical Ophthalmology',
    shortDescription: 'Child-friendly visual acuity screening, lazy eye (Amblyopia) treatment, and squint evaluation.',
    fullDescription: 'Specialized eye care for infants, children, and teenagers. Our child-friendly specialists screen for refractive errors, amblyopia (lazy eye), convergence insufficiency, and computer vision syndrome in young children.',
    benefits: ['Gentle, non-intimidating pediatric examination setting', 'Early detection to prevent irreversible lazy eye', 'Aesthetic and lightweight pediatric frame recommendations'],
    suitableFor: ['Children sitting too close to TVs or rubbing eyes', 'Squinting or head tilting when reading', 'School vision screening follow-up'],
    durationMinutes: 30,
    preparationInfo: 'Gentle pediatric dilating drops may be used; bring your child’s favorite toy or snack.',
    equipmentUsed: 'Streak Retinoscopy & Pediatric Vision Acuity Charts',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Smile'
  },
  {
    name: 'Eye Injuries & Emergency Care',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Emergency Eye Care',
    shortDescription: 'Immediate 24/7 care for ocular trauma, corneal foreign bodies, chemical burns, and sudden vision loss.',
    fullDescription: 'Dedicated rapid-response eye trauma protocol. Whether it is a metal particle, chemical splash, blunt injury, corneal abrasion, or acute red eye with severe pain, our emergency ophthalmic team provides instant medical management and decontamination.',
    benefits: ['Immediate pain relief and specialized ocular decontamination', 'Sterile micro-removal of corneal foreign bodies', 'Emergency surgical triage when required'],
    suitableFor: ['Workplace eye injuries, metal grinding sparks, chemical burns, sudden acute eye pain or vision drop'],
    durationMinutes: 30,
    preparationInfo: 'For chemical splashes, immediately rinse eyes with clean tap water and proceed directly to our hospital. Do NOT rub eyes.',
    equipmentUsed: 'Sterile Foreign Body Removal Station & Emergency Slit Lamp',
    isDiagnostic: false,
    isEmergency: true,
    featured: true,
    icon: 'ShieldAlert'
  },
  {
    name: 'In-House Opticals & Vision Store',
    department: 'Eye Care',
    deptKey: 'eye',
    category: 'Vision & Optical',
    shortDescription: 'Curated international & designer frames, blue-blocker computer lenses, progressives, and contact lenses.',
    fullDescription: 'Located conveniently on the ground floor of Paavai Hospital, our full-service optical boutique provides customized lens fitting, digital pupillometry, polarized sunglasses, anti-reflective coatings, and specialized pediatric eyewear.',
    benefits: ['Precise lens manufacturing tailored to doctor prescription', 'Wide range of affordable to designer frames', 'Express same-day or 24-hour dispensing for standard lenses'],
    suitableFor: ['All patients requiring optical correction, reading glasses, or computer protection glasses'],
    durationMinutes: 20,
    preparationInfo: 'Bring your current prescription or get a fresh refraction done on-site.',
    equipmentUsed: 'Automated Lensometer & Digital Pupillometer',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Glasses'
  },

  // Skin & Aesthetic Services
  // Category 1: Clinical Skin Care
  {
    name: 'Pigmentation & Melasma Treatment',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Skin Care',
    shortDescription: 'Targeted medical therapies, depigmenting peels, and laser toning for stubborn blemishes and sun damage.',
    fullDescription: 'Melasma, post-inflammatory hyperpigmentation (PIH), and sun spots are treated using scientifically validated protocols combining medical-grade topical formulations, chemical peels, and advanced laser toning that targets melanin without compromising skin integrity.',
    benefits: ['Visible reduction in dark patches and uneven tone', 'Safe for Indian skin phototypes (Fitzpatrick III-V)', 'Comprehensive maintenance plan to avoid rebound pigmentation'],
    suitableFor: ['Melasma, freckles, tanning, dark spots from acne, hormonal hyperpigmentation'],
    durationMinutes: 45,
    preparationInfo: 'Avoid excessive sun exposure and discontinue harsh exfoliants 3 days prior.',
    equipmentUsed: 'Q-Switched Laser & Medical Chemical Solutions',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Sun'
  },
  {
    name: 'Chemical Peel Therapy',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Skin Care',
    shortDescription: 'Customized Alpha/Beta Hydroxy acid peels for acne, open pores, dullness, and skin brightening.',
    fullDescription: 'Controlled exfoliation using pharmaceutical-grade peels including Salicylic, Glycolic, Mandelic, and Yellow Peels. These encourage cell renewal, unclog congested pores, reduce oiliness, and reveal fresh, radiant skin.',
    benefits: ['Smoothens skin texture and refines pores', 'Controls active acne and prevents new breakouts', 'Brightens dull and tired complexion'],
    suitableFor: ['Acne-prone skin, dullness, fine lines, uneven texture'],
    durationMinutes: 30,
    preparationInfo: 'Avoid facial waxing or bleaching for 5 days before your chemical peel.',
    equipmentUsed: 'Dermatological Chemical Exfoliation Systems',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Sparkles'
  },
  {
    name: 'Cryotherapy / Intralesional Therapy',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Skin Care',
    shortDescription: 'Controlled liquid nitrogen freezing and targeted intralesional therapy for warts, corns, and cystic acne.',
    fullDescription: 'High-precision cryosurgery using medical liquid nitrogen (-196°C) to safely ablate benign skin lesions, viral warts, and skin tags with minimal downtime. Intralesional injections provide rapid resolution for deep cystic acne and stubborn alopecia areata patches.',
    benefits: ['Quick in-office procedure without general anesthesia', 'Minimal scarring and fast healing', 'Effective for viral warts resistant to topical creams'],
    suitableFor: ['Viral warts, molluscum contagiosum, keloids, localized alopecia areata, skin tags'],
    durationMinutes: 20,
    preparationInfo: 'Keep the area clean. No fasting or special preparation required.',
    equipmentUsed: 'Cryo-Gun Liquid Nitrogen Delivery Unit',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Snowflake'
  },

  // Category 2: Aesthetic & Anti-Aging Treatments
  {
    name: 'Photo Facial / Skin Rejuvenation',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'Intense Pulsed Light & phototherapy to stimulate collagen, fade redness, and enhance natural glow.',
    fullDescription: 'Our medical Photo Facial utilizes precise light wavelengths to target vascular lesions, sun damage, and sluggish collagen synthesis. It delivers a noticeable luminous glow, tightens pore structure, and evens overall skin tone.',
    benefits: ['Zero downtime with immediate post-procedure radiance', 'Stimulates natural deep collagen production', 'Reduces broken capillaries and diffuse facial redness'],
    suitableFor: ['Dull skin, pre-event rejuvenation, sun-damaged skin, early signs of aging'],
    durationMinutes: 45,
    preparationInfo: 'Apply broad-spectrum sunscreen before and after treatment.',
    equipmentUsed: 'Medical IPL & LED Phototherapy Unit',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Zap'
  },
  {
    name: 'Hydra Facial Medical Glow',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'Multi-step vortex hydro-dermabrasion, painless extraction, deep hydration, and antioxidant infusion.',
    fullDescription: 'The gold-standard medical hydra-facial combines non-invasive vortex extraction with deep serum delivery. It dislodges blackheads, dead cellular buildup, and infuses customized hyaluronic acid and antioxidant peptides for an instant glass-skin finish.',
    benefits: ['Instant deep hydration and glass-like skin glow', 'Painless extraction of blackheads and sebum plugs', 'Non-irritating, suitable for all skin types including sensitive skin'],
    suitableFor: ['Bridal preparation, dry/dehydrated skin, congested pores, regular monthly skin maintenance'],
    durationMinutes: 50,
    preparationInfo: 'Come with clean skin without makeup for best results.',
    equipmentUsed: 'Vortex Hydro-Dermabrasion Medical Platform',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Droplet'
  },
  {
    name: 'Laser Hair Removal',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'US-FDA approved painless triple-wavelength diode laser for permanent hair reduction.',
    fullDescription: 'Say goodbye to painful waxing, ingrown hairs, and razor burns. Our state-of-the-art contact-cooled laser system delivers targeted thermal energy to the hair follicle root, ensuring safe, long-lasting hair reduction across all skin tones with minimal discomfort.',
    benefits: ['Up to 90% permanent hair reduction over recommended sessions', 'Contact-cooling tip makes treatment virtually painless', 'Eliminates ingrown hairs and folliculitis'],
    suitableFor: ['Unwanted facial and body hair in women and men, PCOS-related hirsutism'],
    durationMinutes: 40,
    preparationInfo: 'Shave the treatment area 24 hours prior. Do NOT wax, pluck, or thread hair for 3 weeks prior to session.',
    equipmentUsed: 'Triple Wavelength Diode Laser with Ice-Cooling Tip',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Sparkle'
  },
  {
    name: 'Tattoo Removal',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'Safe, high-peak Q-Switched Nd:YAG laser ink fragmentation with minimal scarring.',
    fullDescription: 'Advanced nanosecond Q-Switched laser pulses break down embedded ink pigments into microscopic particles that your body’s lymphatic system naturally eliminates over successive sessions.',
    benefits: ['Effective on black, blue, and colored ink pigments', 'Preserves surrounding healthy skin tissue', 'Topical numbing applied for patient comfort'],
    suitableFor: ['Professional, amateur, or cosmetic tattoo removal and lightening'],
    durationMinutes: 30,
    preparationInfo: 'Topical anesthetic cream applied 30 minutes before the laser session.',
    equipmentUsed: 'Q-Switched Nd:YAG Laser System',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Eraser'
  },
  {
    name: 'Botox & Anti-Wrinkle Injections',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'US-FDA approved botulinum toxin micro-injections for forehead lines, crow’s feet, and frown lines.',
    fullDescription: 'Administered by FRGUHS trained aesthetic physician Dr. Paavai Senthil, botulinum toxin precisely relaxes hyperactive dynamic facial muscles. Smooths away crow’s feet, forehead furrows, and frown lines while maintaining natural facial expressions.',
    benefits: ['Smoother, youthful forehead and eye contours within 5-7 days', 'Prevents permanent static wrinkles from forming', 'Results last 4 to 6 months'],
    suitableFor: ['Forehead wrinkles, frown lines, crow’s feet, bunny lines, excessive underarm sweating (hyperhidrosis)'],
    durationMinutes: 30,
    preparationInfo: 'Avoid blood thinners, alcohol, and vigorous workouts 24 hours before procedure.',
    equipmentUsed: 'Ultra-Fine Micro-Needles & US-FDA Approved Neuromodulators',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'SmilePlus'
  },
  {
    name: 'Threads Treatment (Collagen Lift)',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'Absorbable PDO / PLLA thread lifting for sagging jowls, jawline definition, and collagen stimulation.',
    fullDescription: 'Minimally invasive non-surgical lift using biocompatible polydioxanone (PDO) threads placed under the skin. Provides subtle mechanical lifting while prompting natural neo-collagenesis for prolonged firmness.',
    benefits: ['Non-surgical jawline contouring and mid-face lift', 'Continuous collagen remodeling over 12-18 months', 'Instant noticeable lift with minimal downtime'],
    suitableFor: ['Mild to moderate skin laxity, sagging jowls, nasolabial folds'],
    durationMinutes: 60,
    preparationInfo: 'Local anesthesia is administered. Avoid dental work or facial massage for 2 weeks after.',
    equipmentUsed: 'Medical Grade Absorbable PDO Threads',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Activity'
  },
  {
    name: 'MCT Procedure & Mesotherapy',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Aesthetic Treatments',
    shortDescription: 'Micro-Cannula Transposition & targeted meso-cocktails for under-eye hollows and skin brightening.',
    fullDescription: 'Advanced micro-cannula technique delivers vital vitamins, polynucleotides, and hyaluronic acid directly into the dermal matrix with reduced bruising and swelling. Excellent for under-eye dark circles and stubborn facial dullness.',
    benefits: ['Significantly lower risk of bruising compared to sharp needles', 'Delivers nutrients directly to target tissue layers', 'Rejuvenates tired under-eye hollows and dark circles'],
    suitableFor: ['Under-eye hollowness, dark circles, stubborn facial pigmentation'],
    durationMinutes: 45,
    preparationInfo: 'Apply prescribed pre-treatment skin conditioning cream for 3 days before.',
    equipmentUsed: 'Blunt Micro-Cannula Delivery System',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Injection'
  },

  // Category 3: Hair Treatments
  {
    name: 'GFC Therapy (Growth Factor Concentrate)',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Hair Treatments',
    shortDescription: 'Next-generation acellular growth factor therapy extracted from patient’s own blood for hair regrowth.',
    fullDescription: 'GFC (Growth Factor Concentrate) is an advanced, highly purified biological treatment. Unlike traditional PRP, GFC delivers high concentrations of PDGF, VEGF, EGF, and IGF-1 completely free of RBCs and WBCs, resulting in zero pain, no inflammation, and superior follicle stimulation.',
    benefits: ['Pain-free and 100% autologous biological treatment', 'Significantly higher growth factor concentration than standard PRP', 'Reduces hair fall within 3-4 weeks and stimulates new baby hairs'],
    suitableFor: ['Male and female pattern baldness (Androgenetic Alopecia), thinning hair, telogen effluvium'],
    durationMinutes: 45,
    preparationInfo: 'Wash hair thoroughly with mild shampoo on the morning of treatment. Stay well hydrated.',
    equipmentUsed: 'Automated GFC Centrifugation & Extraction Kits',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Flame'
  },
  {
    name: 'PRP Hair Rejuvenation (Platelet-Rich Plasma)',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Hair Treatments',
    shortDescription: 'Autologous platelet concentrate injections into scalp to revitalize dormant hair follicles.',
    fullDescription: 'Platelet-Rich Plasma therapy utilizes your own blood platelets enriched with bioactive proteins to stimulate miniaturized hair roots, strengthen hair shaft diameter, and prolong the anagen (growth) phase of hair cycles.',
    benefits: ['Natural regenerative treatment utilizing patient’s own plasma', 'Increases hair density and strengthens existing hair shafts', 'Ideal post-hair transplant maintenance'],
    suitableFor: ['Early to moderate hair thinning, diffuse hair loss, postpartum hair shedding'],
    durationMinutes: 45,
    preparationInfo: 'Drink plenty of water before your appointment. Avoid taking aspirin/NSAIDs for 48 hours.',
    equipmentUsed: 'Double-Spin Medical PRP Centrifuge Unit',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Feather'
  },
  {
    name: 'Hair Transplantation (Advanced FUE)',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Hair Treatments',
    shortDescription: 'Precision Follicular Unit Extraction with natural hairline design and high graft survival rates.',
    fullDescription: 'Our surgical team performs advanced Follicular Unit Extraction (FUE) hair transplants. Individual hair follicular units are gently extracted from the donor area (back of the scalp) and implanted into thinning zones following natural angle and depth for undetectable, permanent results.',
    benefits: ['Natural looking hairline customized to facial proportions', 'Permanent lifelong hair growth from DHT-resistant donor follicles', 'No linear scar at the donor site'],
    suitableFor: ['Moderate to advanced male pattern baldness, receding hairlines, beard restoration'],
    durationMinutes: 240,
    preparationInfo: 'Comprehensive pre-operative scalp evaluation and blood profile testing required.',
    equipmentUsed: 'Micro-Motorized FUE Extraction Punches & Implanters',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Scissors'
  },

  // Category 4: Minor Procedures
  {
    name: 'Microneedling / RF Acne Scar Treatment',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Minor Procedures',
    shortDescription: 'Fractional Radiofrequency microneedling to break down fibrous scars and rebuild healthy collagen.',
    fullDescription: 'Combines micro-insulated gold needles with radiofrequency energy delivered at precise depths (0.5mm to 3.5mm). Perfect for remodeling ice-pick, boxcar, and rolling acne scars, as well as reducing enlarged pores and improving skin elasticity.',
    benefits: ['Deep dermal remodeling with minimal epidermal downtime', 'Dramatic improvement in stubborn textured acne scars', 'Safe across Indian skin with reduced risk of hyperpigmentation'],
    suitableFor: ['Acne scars, surgical scars, enlarged pores, skin laxity'],
    durationMinutes: 50,
    preparationInfo: 'Topical anesthetic cream applied for 45 minutes prior for a comfortable experience.',
    equipmentUsed: 'Fractional Micro-Needling Radiofrequency (MNRF) Platform',
    isDiagnostic: false,
    isEmergency: false,
    featured: true,
    icon: 'Layers'
  },
  {
    name: 'Nail Surgery & Ingrown Nail Excision',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Minor Procedures',
    shortDescription: 'Partial nail avulsion with chemical matricectomy for painful ingrown toenails and nail dystrophy.',
    fullDescription: 'Minor surgical correction for recurrent, agonizing ingrown toenails (onychocryptosis). A minor partial lateral nail avulsion combined with phenol matricectomy ensures permanent relief and prevents regrowth at the painful border.',
    benefits: ['Immediate relief from throbbing toe pain and infection', 'Preserves 85% of normal cosmetic nail appearance', 'Prevents recurrent painful ingrown edges permanently'],
    suitableFor: ['Painful ingrown toenails, fungal nail deformities, chronic paronychia'],
    durationMinutes: 30,
    preparationInfo: 'Performed under quick local digital nerve block. Wear open-toed footwear to your appointment.',
    equipmentUsed: 'Sterile Minor Dermatosurgical Instrument Kit & Chemical Matricectomy Reagents',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Shield'
  },
  {
    name: 'Earlobe Repair (Sutureless & Surgical)',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Minor Procedures',
    shortDescription: 'Aesthetic repair of torn, stretched, or split earlobes with same-day repiercing options.',
    fullDescription: 'Quick, painless in-office restoration of elongated, torn, or completely split earlobes caused by heavy earrings or accidental trauma. Utilizing delicate surgical reconstruction or surgical glue techniques for minimal scar visibility.',
    benefits: ['Painless 20-minute procedure under local anesthesia', 'Aesthetically pleasing earlobe contour restoration', 'Repiercing guidance provided after complete healing'],
    suitableFor: ['Stretched piercing holes, partially or completely split earlobes'],
    durationMinutes: 25,
    preparationInfo: 'Do not wear heavy ear jewelry on the day of appointment.',
    equipmentUsed: 'Fine Dermatosurgical Instruments & Micro-Sutures',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Heart'
  },
  {
    name: 'Keloid Surgery & Intralesional Injections',
    department: 'Skin Care',
    deptKey: 'skin',
    category: 'Minor Procedures',
    shortDescription: 'Multimodal therapy combining surgical debulking, intralesional anti-fibrotic agents, and cryotherapy.',
    fullDescription: 'Keloids and hypertrophic scars can be itchy, painful, and cosmetically distressing. We offer combined therapeutic modalities: intralesional corticosteroid and 5-FU infusions, cryosurgery, and core keloid excision to flatten thick scars and stop itching.',
    benefits: ['Flattens thick, elevated scars and relieves chronic itching/tenderness', 'Multimodal protocol drastically lowers keloid recurrence rates', 'Tailored to earlobe, chest, and shoulder keloids'],
    suitableFor: ['Keloids on earlobes, chest, back, or shoulders from acne, piercings, or surgery'],
    durationMinutes: 30,
    preparationInfo: 'Keep the area clean. Regular follow-up sessions may be scheduled 3-4 weeks apart.',
    equipmentUsed: 'Precision Intralesional Delivery Syringes & Cryo Equipment',
    isDiagnostic: false,
    isEmergency: false,
    featured: false,
    icon: 'Activity'
  }
];

const sampleAppointmentsData = [
  {
    appointmentRef: 'PVH-2025-081421',
    department: 'Skin Care',
    doctorName: 'Dr. Paavai Senthil',
    serviceName: 'Hydra Facial Medical Glow',
    appointmentDate: new Date().toISOString().split('T')[0],
    timeSlot: '10:30 AM',
    patientName: 'Karthik Subramanian',
    patientPhone: '+91 98421 78901',
    patientEmail: 'karthik.sub@gmail.com',
    patientAge: 29,
    patientGender: 'Male',
    visitType: 'First Visit (New Consultation)',
    reasonNotes: 'Skin dullness and blackhead congestion on nose and forehead.',
    status: 'Confirmed',
    tokenNumber: 'SK-01',
    paymentStatus: 'Pay at Hospital Counter'
  },
  {
    appointmentRef: 'PVH-2025-081422',
    department: 'Eye Care',
    doctorName: 'Dr. R. Soundararajan',
    serviceName: 'Advanced Cataract Surgery & Evaluation',
    appointmentDate: new Date().toISOString().split('T')[0],
    timeSlot: '11:15 AM',
    patientName: 'Meenakshi Sundaram',
    patientPhone: '+91 94432 54321',
    patientEmail: 'meenakshi.s@yahoo.com',
    patientAge: 64,
    patientGender: 'Female',
    visitType: 'First Visit (New Consultation)',
    reasonNotes: 'Cloudy vision in right eye since 4 months, difficulty in driving at night.',
    status: 'Confirmed',
    tokenNumber: 'EY-01',
    paymentStatus: 'Pay at Hospital Counter'
  },
  {
    appointmentRef: 'PVH-2025-081423',
    department: 'Skin Care',
    doctorName: 'Dr. Nivas Sengottaiyan',
    serviceName: 'Pigmentation & Melasma Treatment',
    appointmentDate: new Date().toISOString().split('T')[0],
    timeSlot: '04:30 PM',
    patientName: 'Priya Rajendran',
    patientPhone: '+91 97890 12345',
    patientEmail: 'priya.raj@outlook.com',
    patientAge: 34,
    patientGender: 'Female',
    visitType: 'Follow-up Checkup',
    reasonNotes: 'Review of pigmentation serum response and chemical peel scheduling.',
    status: 'Confirmed',
    tokenNumber: 'SK-02',
    paymentStatus: 'Pay at Hospital Counter'
  }
];

async function seedDatabase() {
  try {
    const doctorCount = await Doctor.countDocuments();
    if (doctorCount === 0) {
      console.log('Seeding doctors collection...');
      await Doctor.insertMany(doctorsData);
      console.log('Doctors seeded successfully!');
    }

    const serviceCount = await Service.countDocuments();
    if (serviceCount === 0) {
      console.log('Seeding services collection...');
      await Service.insertMany(servicesData);
      console.log('Services seeded successfully!');
    }

    const appointmentCount = await Appointment.countDocuments();
    if (appointmentCount === 0) {
      console.log('Seeding sample appointments...');
      await Appointment.insertMany(sampleAppointmentsData);
      console.log('Sample appointments seeded successfully!');
    }
  } catch (err) {
    console.error('Error seeding database:', err);
  }
}

module.exports = { seedDatabase, doctorsData, servicesData, sampleAppointmentsData };
